// エクスポートユーティリティ
class ExportUtils {
    static exportAsFile(filename, content) {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        
        return filename;
    }
    
    static exportAsZip(files) {
        // シンプルな実装（実際にはJSZipなどのライブラリを使用）
        const zipContent = files.map(file => 
            `=== ${file.filename} ===\n${file.content}\n\n`
        ).join('\n');
        
        return this.exportAsFile('discord-bot-package.txt', zipContent);
    }
    
    static generateCompletePackage(code, language, botName = 'MyDiscordBot') {
        const files = [];
        const now = new Date().toISOString().split('T')[0];
        
        // メインファイル
        const mainFilename = this.getMainFilename(language);
        files.push({
            filename: mainFilename,
            content: code
        });
        
        // package.json / requirements.txt
        const configFile = this.generateConfigFile(language, botName);
        files.push({
            filename: configFile.filename,
            content: configFile.content
        });
        
        // .env.example
        files.push({
            filename: '.env.example',
            content: this.generateEnvExample()
        });
        
        // README.md
        const readme = CodeFormatter.generateReadme(code, language, botName);
        files.push({
            filename: 'README.md',
            content: readme
        });
        
        // .gitignore
        files.push({
            filename: '.gitignore',
            content: this.generateGitignore(language)
        });
        
        return files;
    }
    
    static getMainFilename(language) {
        switch(language) {
            case 'javascript':
                return 'bot.js';
            case 'typescript':
                return 'bot.ts';
            case 'python':
                return 'bot.py';
            default:
                return 'bot.js';
        }
    }
    
    static generateConfigFile(language, botName) {
        switch(language) {
            case 'javascript':
                return {
                    filename: 'package.json',
                    content: JSON.stringify({
                        name: botName.toLowerCase().replace(/\s+/g, '-'),
                        version: '1.0.0',
                        description: 'Discord bot generated by Discord Bot Builder',
                        main: 'bot.js',
                        scripts: {
                            start: 'node bot.js'
                        },
                        dependencies: {
                            'discord.js': '^14.13.0'
                        },
                        keywords: ['discord', 'bot'],
                        author: 'Discord Bot Builder',
                        license: 'MIT'
                    }, null, 2)
                };
                
            case 'typescript':
                return {
                    filename: 'package.json',
                    content: JSON.stringify({
                        name: botName.toLowerCase().replace(/\s+/g, '-'),
                        version: '1.0.0',
                        description: 'Discord bot generated by Discord Bot Builder',
                        main: 'dist/bot.js',
                        scripts: {
                            build: 'tsc',
                            start: 'node dist/bot.js',
                            dev: 'ts-node bot.ts'
                        },
                        dependencies: {
                            'discord.js': '^14.13.0',
                            'dotenv': '^16.3.1'
                        },
                        devDependencies: {
                            'typescript': '^5.1.6',
                            'ts-node': '^10.9.1',
                            '@types/node': '^20.4.5'
                        },
                        keywords: ['discord', 'bot', 'typescript'],
                        author: 'Discord Bot Builder',
                        license: 'MIT'
                    }, null, 2)
                };
                
            case 'python':
                return {
                    filename: 'requirements.txt',
                    content: `discord.py>=2.3.2
python-dotenv>=1.0.0`
                };
                
            default:
                return { filename: '', content: '' };
        }
    }
    
    static generateEnvExample() {
        return `# Discord Bot Token
# 取得方法: https://discord.com/developers/applications
DISCORD_TOKEN=your_bot_token_here

# Bot Prefix (Optional)
BOT_PREFIX=!

# その他の環境変数
# LOG_LEVEL=info`;
    }
    
    static generateGitignore(language) {
        let content = `# 環境変数
.env
.env.local
.env.*.local

# ログファイル
*.log
logs/

# ランタイムデータ
data/
tmp/
temp/`;

        switch(language) {
            case 'javascript':
                content += '\n\n# Node.js\nnode_modules/\nnpm-debug.log*\n';
                break;
            case 'typescript':
                content += '\n\n# TypeScript\ndist/\nnode_modules/\n*.tsbuildinfo\n';
                break;
            case 'python':
                content += '\n\n# Python\n__pycache__/\n*.py[cod]\n*.so\n.Python\n';
                break;
        }
        
        return content;
    }
    
    static exportToClipboard(text) {
        return navigator.clipboard.writeText(text)
            .then(() => true)
            .catch(err => {
                console.error('クリップボードへのコピーに失敗しました:', err);
                return false;
            });
    }
    
    static createDownloadLink(text, filename, elementId = null) {
        const blob = new Blob([text], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        
        if (elementId) {
            const link = document.getElementById(elementId);
            if (link) {
                link.href = url;
                link.download = filename;
                return link;
            }
        }
        
        return url;
    }
    
    static generatePreview(code, language) {
        // コードプレビュー用のHTML生成
        const escapedCode = code
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#039;');
        
        return `<pre class="language-${language}"><code>${escapedCode}</code></pre>`;
    }
}
